# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03cc1e760de34f6ee2e56e1b885e07e4e723eee28b3818e3c77f09e1eb7a3c7fd0e22294fcbae0845c5dd59dc117d7638028b58295a844c8791bd277d657d607

test:
  secret_key_base: 2827cb69d6eecc2fd9b758ee31c0fff37de70063986bda8b63400c060cf2ca2516dbce7906fb8b7da3fbc2f0302683c21fb085e700fa26a5a6ec50e3c0177f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
